server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: fams
  security:
   oauth2:
     client:
       registration:
         google:
           clientId: 860713489001-sorblkaslpt2l79hf3ghn31ukcp38l71.apps.googleusercontent.com
           clientSecret: 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
          #  redirectUriTemplate: "{baseUrl}/login/oauth2/code/{registrationId}"
           scope:
             - email
             - profile
         facebook:
          clientId: 1023601369226468
          clientSecret: 763e3d4d2916c22bcf1fc4e2263b848c
          scope:
           - email
           - public_profile