server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: fams
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 860713489001-sorblkaslpt2l79hf3ghn31ukcp38l71.apps.googleusercontent.com
            clientSecret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            client-name: Google
          facebook:
            clientId: 1023601369226468
            clientSecret: 763e3d4d2916c22bcf1fc4e2263b848c
            scope:
              - email
              - public_profile
            client-name: Facebook
            provider: facebook
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v12.0/dialog/oauth
            token-uri: https://graph.facebook.com/v12.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/v12.0/me?fields=id,name,email,picture
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
